# Generated by Django 4.1.4 on 2023-07-07 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='checkOut',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='purpose',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default='16:13:02'),
        ),
    ]
