# Generated by Django 4.1.4 on 2023-07-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_entry_checkout_entry_purpose_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default='16:40:41'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='checkOut',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
